if (self.CavalryLogger) { CavalryLogger.start_js(["qtl+e"]); }

__d("useLiveVideoCometInstreamRewardAlertDisplay",["createVideoStateHook"],(function(a,b,c,d,e,f){"use strict";a=b("createVideoStateHook").createVideoStateHook(null);c=a.setterHook;d=a.valueHook;e=c;f.useInstreamRewardAlertDisplayStateSetter=e;b=d;f.useInstreamRewardAlertDisplayStateValue=b}),null);
__d("validatePlayerSuborigin",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return typeof a==="string"?a:null}}),null);
__d("CometVideoCommentComposerGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){a=a.index;return g.jsx("div",{className:"j9ispegn pmk7jnqg dhix69tm bi6gxh9e wkznzc2l kvgmc6g5 n7fi1qx3 i09qtzwb",children:g.jsxs("div",{className:"j83agx80 bp9cbjyn",children:[g.jsx(b("BaseGlimmer.react"),{className:"q676j6op oi9244e8 qypqp5cg pfnyh3mw spb7xbtv bkmhp75w emlxlaya s45kfl79",index:a}),g.jsx(b("BaseGlimmer.react"),{className:"l5sxq0ai tv7at329 buofh1pr gob819ct ols5edhi gmcszhul emml16de",index:a})]})})}}),null);
__d("CometVideoProfileInfoGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){var c;a=a.index;return g.jsxs("div",{className:"cbu4d94t j83agx80",children:[g.jsxs("div",{className:"j83agx80",children:[g.jsx(c=b("BaseGlimmer.react"),{className:"go5t5npl oi9244e8 hxdsxuhi spb7xbtv bkmhp75w emlxlaya s45kfl79",index:a}),g.jsxs("div",{className:"taijpn5t cbu4d94t j83agx80",children:[g.jsx(c,{className:"elpiyq4v bi6gxh9e cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a}),g.jsx(c,{className:"i7o4yfgj cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a})]})]}),g.jsx(c,{className:"f4c7eilb n1l5q3vz jnigpg78 ns4ygwem fykbt5ly hgaippwi fni8adji",index:a})]})}}),null);
__d("CometTahoeUpNextItemGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a;return g.jsxs("div",{className:"tr9rh885 j83agx80",children:[g.jsx(a=b("BaseGlimmer.react"),{className:"m7fg4r8v tvfksri0 ic2jb53e qttc61fc ihh4hy1g kdgqqoy6 jk6sbkaj",index:0}),g.jsxs("div",{children:[g.jsx(a,{className:"bow6oqyw gl3lb2sf l82x9zwi uo3d90p7 pw54ja7n ue3kfks5",index:0}),g.jsx(a,{className:"nx96mzau ku2m03ct cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:0}),g.jsx(a,{className:"lelwyktv ku2m03ct cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:0})]})]})}}),null);
__d("CometTahoeUpNextGlimmer.react",["BaseGlimmer.react","CometTahoeUpNextItemGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h=3;function a(){return g.jsxs("div",{className:"cbu4d94t j83agx80",children:[g.jsx(b("BaseGlimmer.react"),{className:"bow6oqyw gl3lb2sf l82x9zwi uo3d90p7 pw54ja7n ue3kfks5",index:0}),Array(h).fill().map(function(a,c){return g.jsx(b("CometTahoeUpNextItemGlimmer.react"),{},c)})]})}}),null);
__d("CometTahoeSidePaneGlimmer.react",["CometTahoeUpNextGlimmer.react","CometVideoCommentComposerGlimmer.react","CometVideoProfileInfoGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){return g.jsxs("div",{className:"dhix69tm sjgh65i0 wkznzc2l tr9rh885 cbu4d94t j83agx80",children:[g.jsx("div",{className:"tfnaxnde",children:g.jsx(b("CometVideoProfileInfoGlimmer.react"),{index:0})}),g.jsx(b("CometTahoeUpNextGlimmer.react"),{}),g.jsx("div",{className:"pmk7jnqg lfi1tu6t",children:g.jsx(b("CometVideoCommentComposerGlimmer.react"),{index:0})})]})}}),null);
__d("VideoSharingOptionClickedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744466");c=b("FalcoLoggerInternal").create("video_sharing_option_clicked",a);e.exports=c}),null);
__d("VideoSharingOptionImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744467");c=b("FalcoLoggerInternal").create("video_sharing_option_impression",a);e.exports=c}),null);
__d("VideoHomeShareUtils",["VideoSharingOptionClickedFalcoEvent","VideoSharingOptionImpressionFalcoEvent"],(function(a,b,c,d,e,f){"use strict";a=function(a){var c=a.player_origin,d=a.reaction_video_channel_type,e=a.video_player_format,f=babelHelpers["extends"]({},a,{player_origin:c==null?void 0:c.toString(),reaction_video_channel_type:d==null?void 0:d.toString(),video_player_format:e==null?void 0:e.toString()});b("VideoSharingOptionImpressionFalcoEvent").log(function(){return f})};f.logExternalShareOptionImpression=a;c=function(a){var c=a.player_origin,d=a.reaction_video_channel_type,e=a.video_player_format,f=babelHelpers["extends"]({},a,{player_origin:c==null?void 0:c.toString(),reaction_video_channel_type:d==null?void 0:d.toString(),video_player_format:e==null?void 0:e.toString()});b("VideoSharingOptionClickedFalcoEvent").log(function(){return f})};f.logExternalShareOptionClick=c}),null);
__d("VideoSharingPermalinkLandingFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744468");c=b("FalcoLoggerInternal").create("video_sharing_permalink_landing",a);e.exports=c}),null);
__d("CometVideoHomeShareUtils",["ConstUriUtils","VideoHomeShareUtils","VideoSharingPermalinkLandingFalcoEvent"],(function(a,b,c,d,e,f){"use strict";var g="extid";a=function(a){var c=b("ConstUriUtils").getUri(window.location.href),d=(c==null?void 0:c.getQueryParam(g))!=null;c!=null&&d&&h(babelHelpers["extends"]({},a,{url:c.toString()}))};var h=function(a){b("VideoSharingPermalinkLandingFalcoEvent").log(function(){return a})};e.exports={logExternalShareOptionClick:b("VideoHomeShareUtils").logExternalShareOptionClick,logExternalShareOptionImpression:b("VideoHomeShareUtils").logExternalShareOptionImpression,logPermalinkLandingFromSharing:h,logPermalinkLandingFromSharingIfQueryParamExists:a,sharingTrackingParam:g}}),null);