if (self.CavalryLogger) { CavalryLogger.start_js(["AJKs2"]); }

__d("EventCometDashboardRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2930368140396422",metadata:{},name:"EventCometDashboardRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("BirthdayCometRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3382519521824494",metadata:{},name:"BirthdayCometRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometHomeRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3238884356240140",metadata:{},name:"EventCometHomeRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometBirthdayMegaphoneRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3273322056112474",metadata:{},name:"EventCometBirthdayMegaphoneRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCometEventDashboardRoute.entrypoint",["JSResource","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","EventCometDashboardRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResource")("EventCometDashboardRoot.react").__setRef("buildCometEventDashboardRoute.entrypoint"),function(){return{queryReference:{parameters:b("EventCometDashboardRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get(),upcomingEventsCount:3}}}});e.exports=a}),null);
__d("EventCometFullPageEntryPointCompatRoot.entrypoint",["JSResource","buildCometEventDashboardRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometEventDashboardRoute.entrypoint")(b("JSResource")("CometFullPageEntryPointCompatRoot.react").__setRef("EventCometFullPageEntryPointCompatRoot.entrypoint"),function(a){a=a.routeProps.maintainKey;return{extraProps:{routeProps:{maintainKey:a}}}});e.exports=a}),null);
__d("BirthdayCometRoot.entrypoint",["JSResource","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","BirthdayCometRootQuery$Parameters","EventCometBirthdayMegaphoneRootQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometEventDashboardRoute.entrypoint")(b("JSResource")("BirthdayCometRoot.react").__setRef("BirthdayCometRoot.entrypoint"),function(a){return{queries:{birthdayQueryReference:{parameters:b("BirthdayCometRootQuery$Parameters"),variables:{offset_month:new Date().getMonth()+1,scale:b("WebPixelRatio").get()}},megaphoneQueryReference:{parameters:b("EventCometBirthdayMegaphoneRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}}}}});e.exports=a}),null);
__d("EventCometHomeRoot.entrypoint",["JSResource","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","gkx","qex","EventCometHomeRootQuery$Parameters","VideoChatHomeContainerCometQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";var g=7775;a=b("buildCometEventDashboardRoute.entrypoint")(b("JSResource")("EventCometHomeRoot.react").__setRef("EventCometHomeRoot.entrypoint"),function(){var a={first:10,nuxID:g,scale:b("WebPixelRatio").get()};a={homeQueryReference:{parameters:b("EventCometHomeRootQuery$Parameters"),variables:a}};if(b("gkx")("1445734")){var c;a=babelHelpers["extends"]({},a,{joinableVideoChatsQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:b("VideoChatHomeContainerCometQuery$Parameters"),variables:{enableMultipleRooms:(c=b("qex")._("1624805"))!=null?c:!1,scale:b("WebPixelRatio").get(),show_with_active_room:!0}}})}return{queries:a}});e.exports=a}),null);